---
Description: 'AWS CloudFormation Sample Template to create EC2 Instance to an imported
  Subnet: Create an Amazon EC2 instance running the Amazon Linux AMI. The AMI is chosen
  based on the region in which the stack is run. This example launches an EC2 instance
  in an imported/refered Subnet. **WARNING** This template creates an Amazon EC2 instance.
  You will be billed for the AWS resources used if you create a stack from this template.'
Parameters:
  VPCSubnetId:
    Description: Subnet ID list
    Type: AWS::EC2::Subnet::Id
    Default: subnet-d5ee6ab2
    ConstraintDescription: must be an existing subnet.
  EC2SecurityGroupIds:
    Description: Security Group Id's
    Type: AWS::EC2::SecurityGroup::Id
    Default: sg-6e9eb617
    ConstraintDescription: must be an existing security group.
  AMI:
    Description: Amazon Machine Image
    Type: String
    Default: ami-307fa852
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
    - t2.nano
    - t2.micro
    - t2.small
    - t2.medium
    - t2.large
    ConstraintDescription: must be a valid EC2 instance type.
  KeyName:
    Description: Name of an existing EC2 KeyPair to access the instance
    Type: "AWS::EC2::KeyPair::KeyName"
Resources:
  EC2InstanceUserData:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType:
        Ref: InstanceType
      SubnetId:
        Ref: VPCSubnetId
      SecurityGroupIds:
      - Ref: EC2SecurityGroupIds
      ImageId:
        Ref: AMI
      KeyName: !Ref KeyName
      Tags:
            - Key: Name
              Value: !Ref AWS::StackName
      UserData:
        Fn::Base64: !Sub |
                  <powershell>
                  "AWS Userdata Test" > C:\UserdataOutput.txt
                  Install-WindowsFeature -name Web-Server -IncludeManagementTools
                  </powershell>
Outputs:
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value:
      Ref: EC2InstanceUserData
